config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :merge_runners_requests do
    member do
      get 'accept'
    end
  end
  resources :categories
  resources :runs
  resources :runners do
    collection do
      get 'show_remembered'
    end
  end
  get 'welcome/index'

  root 'runners#index'

end

app/models/runner.rb
class Runner < ActiveRecord::Base
  # TODO: use run_day.date for ordering, seems to be tough to do since it needs another join.
  has_many :runs, -> { order(run_day_id: :asc) }
  has_many :categories, through: :runs
  has_many :run_days, through: :runs
  has_and_belongs_to_many :merge_runners_requests

  def fastest_run
    runs.min_by { |i| i.duration || 0 }
  end

  def mean_run_duration
    runs.average(:duration) || 0
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show]

  # GET /runners
  # GET /runners.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: RunnerDatatable.new(view_context) }
    end
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
    @chart = ShowRunnerChart.new(@runner)
  end

  def show_remembered
    if cookies[:remembered_runners]
      runner_ids = JSON.parse(cookies[:remembered_runners]).keys
      @runners = RunnersDecorator.decorate(Runner.includes(:runs, :run_days).find(runner_ids))
    else
      @runners = []
    end
    @chart = CompareRunnersChart.new(@runners)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.includes(runs: [:category, :run_day, :run_day_category_aggregate]).find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:first_name, :last_name, :birth_date, :sex)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
  def ruby_to_javascript_date(date)
    # Tricky: months are 1 based in ruby, but 0 based in javascript
    "Date.UTC(#{date.year}, #{date.month - 1}, #{date.day})"
  end
end

app/views/runners/index.html.erb
<h1>Listing Runners</h1>
<div class="row">
  <div class="col-lg-9">
    <table class="table table-hover" id="runners-datatable" data-source="<%= runners_path(format: :json) %>">
      <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Club or hometown</th>
        <th>Sex</th>
        <th>Nationality</th>
        <th>Participations</th>
        <th>Best time</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      </tbody>
    </table>
  </div>
  <div class="col-lg-3">
    <%= panel heading: 'Remembered runners', context: :info, id: 'remembered-runners-panel' do %>
        <div class='panel-body'>
          <%= link_to t('.show_remembered_runners'), show_remembered_runners_path, class: 'btn btn-primary btn-block' %>
          <%= link_to t('.forget_remembered_runners'), '#', data: {forget_runners: true}, class: 'btn btn-danger btn-block' %>
          <%= link_to t('.merge_remembered_runners'), new_merge_runners_request_path, class: 'btn btn-default btn-xs btn-block' %>
        </div>
    <% end %>
  </div>
</div>

app/views/runners/show.html.erb
<h1><%= @runner.first_name %> <%= @runner.last_name %></h1>
<dl class="dl-horizontal">
  <dt><%= Runner.human_attribute_name :birth_date %></dt>
  <dd><%= I18n.l @runner.birth_date %></dd>
  <dt><%= Runner.human_attribute_name :sex %></dt>
  <dd><%= @runner.sex %></dd>
  <dt><%= Runner.human_attribute_name :club_or_hometown %></dt>
  <dd><%= @runner.club_or_hometown %></dd>
</dl>

<h2>Runs</h2>

<% if @runner.runs.empty? %>
    No runs available
<% else %>
    <div id="runs_chart" style="width:100%; height:300px;"></div>
    <%= high_chart("runs_chart", @chart)  %>
    <table class="table table-striped">
      <thead>
      <th><%= Run.human_attribute_name :run_date %></th>
      <th><%= RunDay.human_attribute_name :weather %></th>
      <th><%= Run.human_attribute_name :category %></th>
      <th><%= Run.human_attribute_name :duration %></th>
      </thead>
      <% @runner.runs.each do |run| %>
          <tr>
            <td><%= I18n.l run.run_day.date %></td>
            <td><%= run.run_day.weather %></td>
            <td><%= run.category.name %></td>
            <td><%= run.duration_formatted %></td>
          </tr>
      <% end %>
    </table>
<% end %>
<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>

app/views/runners/show_remembered.html.erb
<div id="runs_chart" style="width:100%; height:300px;"></div>
<%= high_chart("runs_chart", @chart)  %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Runner.human_attribute_name(:name) %></th>
    <th><%= Runner.human_attribute_name(:club_or_hometown) %></th>
    <th><%= Runner.human_attribute_name(:nationality) %></th>
    <th><%= Runner.human_attribute_name(:runs_count) %></th>
    <th><%= Runner.human_attribute_name(:mean_run_duration) %></th>
  </tr>
  </thead>
  <tbody>
  <% @runners.each do |runner| %>
      <tr>
        <td><%= runner.name %></td>
        <td><%= runner.club_or_hometown %></td>
        <td><%= runner.nationality %></td>
        <td><%= runner.runs_count %></td>
        <td><%= runner.mean_run_duration %></td>
      </tr>
  <% end %>
  </tbody>
</table>