config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :merge_runners_requests do
    member do
      get 'accept'
    end
  end
  resources :categories
  resources :runs
  resources :runners do
    collection do
      get 'show_remembered'
    end
  end
  get 'welcome/index'

  root 'runners#index'

end

app/models/merge_runners_request.rb
class MergeRunnersRequest < ActiveRecord::Base
  has_and_belongs_to_many :runners
  has_many :runs, through: :runners

  INHERITED_ATTRIBUTES = [:first_name, :last_name, :nationality, :sex, :club_or_hometown, :birth_date]
  VALID_SEXES = %w(M W)

  validates_presence_of *INHERITED_ATTRIBUTES.map { |attr| "merged_#{attr}" }
  # TODO: Add validation for non-intersecting run days
  # TODO: Add possibly validation for edit-distance between merged and inherited attribute name.
  validates :merged_nationality, format: /\A[A-Z]{3}\z/
  validates :merged_sex, inclusion: { in: VALID_SEXES }
  validates_with MergeRunnersRequestsRunDaysValidator

  def self.new_from(merge_candidates)
    # Select most runner with most recent run as default for attributes of merge requests.
    best_mc = merge_candidates.max_by { |mc| mc.run_days.max_by(&:date) }
    # TODO: possibly do something more sophisticated with birth_date.
    merge_request_defaults = INHERITED_ATTRIBUTES.each_with_object({}) { |attr, hash| hash["merged_#{attr}"] = best_mc[attr] }
    merge_request_defaults[:runners] = merge_candidates
    self.new(merge_request_defaults)
  end

  # Instantiates a new runner with data from this merge request and associates all runs with the new instance. Still
  # needs to be saved in order to be written to DB!
  def to_new_runner
    runner_attributes = INHERITED_ATTRIBUTES.each_with_object({}) { |attr, hash| hash[attr] = self["merged_#{attr}"] }
    runner_attributes[:runs] = runs
    Runner.new(runner_attributes)
  end
end

app/controllers/merge_runners_requests_controller.rb
class MergeRunnersRequestsController < ApplicationController
  before_action :set_merge_runner_request, only: [:show, :edit, :update, :destroy, :accept]
  before_action :authenticate_admin!, except: [:new, :create]

  # GET /merge_runner_requests
  def index
    @merge_runners_requests = MergeRunnersRequest.all.decorate
  end

  # GET /merge_runner_requests/1
  def show
    @merge_runners_request = @merge_runners_request.decorate
  end

  # GET /merge_runner_requests/new
  def new
    merge_candidates = Runner.includes(:run_days).find(JSON.parse(cookies[:remembered_runners] || '{}').keys)
    @merge_runners_request = MergeRunnersRequest.new_from(merge_candidates)
    @merge_runners_request.validate
    if @merge_runners_request.errors[:runners].any?
      # Runners can not be merged, show them instead.
      flash[:error] = @merge_runners_request.errors[:runners]
      redirect_to show_remembered_runners_path
    end
  end

  # GET /merge_runner_requests/1/edit
  def edit
  end

  # POST /merge_runner_requests
  def create
    @merge_runners_request = MergeRunnersRequest.new(merge_runner_request_params)

    if @merge_runners_request.save
      # Delete cookie.
      cookies[:remembered_runners] = nil
      redirect_to runners_path, notice: 'Merge runner request was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /merge_runner_requests/1
  def update
    if @merge_runners_request.update(merge_runner_request_params)
      redirect_to @merge_runners_request, notice: 'Merge runner request was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /merge_runner_requests/1
  def destroy
    @merge_runners_request.destroy
    redirect_to merge_runners_requests_url, notice: 'Merge runner request was successfully destroyed.'
  end

  def accept
    new_runner = @merge_runners_request.to_new_runner
    if new_runner.save!
      @merge_runners_request.runners.each &:destroy!
      flash[:info] = 'Successfully merged runner'
      redirect_to runner_path(new_runner)
    else
      flash[:error] = 'Could not create new runner: ' + new_runner.errors
      redirect_to merge_runners_requests_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merge_runner_request
      @merge_runners_request = MergeRunnersRequest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def merge_runner_request_params
      params.require(:merge_runners_request).permit(:merged_first_name, :merged_last_name, :merged_club_or_hometown,
                                                    :merged_nationality, :merged_sex, :merged_birth_date, runner_ids: [])
    end
end

app/helpers/merge_runners_requests_helper.rb
module MergeRunnersRequestsHelper

  MERGE_CANDIDATES_SHOWN_ATTRIBUTES = [:first_name, :last_name, :club_or_hometown, :sex, :nationality]

  def merge_candidates_table(merge_candidates)
    content_tag :table, class: 'table table-hover' do
      MERGE_CANDIDATES_SHOWN_ATTRIBUTES.map do |attr|
        content_tag :tr do
          content_tag(:th, Runner.human_attribute_name(attr)) <<
                             merge_candidates.each.map { |mc| content_tag :td, mc.send(attr) }.join.html_safe
        end
      end.join.html_safe
    end
  end
end

app/views/merge_runners_requests/_form.html.erb
<%= merge_candidates_table(@merge_runners_request.runners) %>
<% if @merge_runners_request.errors[:runners].any? %>
    <%= alert_box @merge_runners_request.errors[:runners].join(', '), context: :danger %>
<% end %>
<%= horizontal_simple_form_for(@merge_runners_request) do |f| %>
    <% @merge_runners_request.runner_ids.each do |id| %>
        <%= f.hidden_field :runner_ids, multiple: true, value: id %>
    <% end %>
    <%= f.hidden_field :merged_birth_date %>
    <%= f.input :merged_first_name %>
    <%= f.input :merged_last_name %>
    <%= f.input :merged_club_or_hometown %>
    <%= f.input :merged_sex, collection: MergeRunnersRequest::VALID_SEXES, include_blank: false %>
    <%= f.input :merged_nationality %>
    <div class="pull-right">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/merge_runners_requests/edit.html.erb
<h1>Editing Merge Runner Request</h1>

<%= render 'form' %>

<%= link_to 'Show', merge_runners_request_path(@merge_runners_request) %> |
<%= link_to 'Back', merge_runners_requests_path %>

app/views/merge_runners_requests/index.html.erb
<h1>Listing Merge Runner Requests</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Merged first name</th>
      <th>Merged last name</th>
      <th>Merged club or hometown</th>
      <th>Merged nationality</th>
      <th>Merged sex</th>
      <th>Merge candidates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merge_runners_requests.each do |merge_runners_request| %>
      <tr>
        <td><%= merge_runners_request.merged_first_name %></td>
        <td><%= merge_runners_request.merged_last_name %></td>
        <td><%= merge_runners_request.merged_club_or_hometown %></td>
        <td><%= merge_runners_request.merged_nationality %></td>
        <td><%= merge_runners_request.merged_sex %></td>
        <td><%= merge_runners_request.runners %></td>
        <td><%= link_to 'Show', merge_runners_request_path(merge_runners_request) %></td>
        <td><%= link_to 'Edit', edit_merge_runners_request_path(merge_runners_request) %></td>
        <td><%= link_to 'Accept', accept_merge_runners_request_path(merge_runners_request),
                        data: { confirm: 'Are you sure you want to accept?' } %></td>
        <td><%= link_to 'Destroy', merge_runners_request_path(merge_runners_request),
                        method: :delete, data: { confirm: 'Are you sure you want delete?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merge runner request', new_merge_runners_request_path %>

app/views/merge_runners_requests/new.html.erb
<h1>New Merge Runner Request</h1>

<%= render 'form' %>

<%= link_to 'Back', merge_runners_requests_path %>

app/views/merge_runners_requests/show.html.erb
<p>
  <strong>Merged first name:</strong>
  <%= @merge_runners_request.merged_first_name %>
</p>

<p>
  <strong>Merged last name:</strong>
  <%= @merge_runners_request.merged_last_name %>
</p>

<p>
  <strong>Merged club or hometown:</strong>
  <%= @merge_runners_request.merged_club_or_hometown %>
</p>

<p>
  <strong>Merged nationality:</strong>
  <%= @merge_runners_request.merged_nationality %>
</p>

<p>
  <strong>Merged sex:</strong>
  <%= @merge_runners_request.merged_sex %>
</p>

<p>
  <strong>Merge candidates:</strong>
  <%= @merge_runners_request.runners %>
</p>

<%= link_to 'Edit', edit_merge_runners_request_path(@merge_runners_request) %> |
<%= link_to 'Back', merge_runners_requests_path %>