config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :merge_runners_requests do
    member do
      get 'accept'
    end
  end
  resources :categories
  resources :runs
  resources :runners do
    collection do
      get 'show_remembered'
    end
  end
  get 'welcome/index'

  root 'runners#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GpCollect</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-67613944-1', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>
<%= navbar do %>
    <%= vertical do %>
        <%= link_to 'GP collect', root_path %>
    <% end %>
    <%= horizontal do %>
        <%= nav do %>
            <%= link_to 'Runners', runners_path %>
            <%= link_to 'Categories', categories_path %>
        <% end %>
        <%= nav class: 'navbar-right' do %>
            <% if current_admin %>
                <%= link_to 'Logout', destroy_admin_session_path, method: 'delete' %>
            <% else %>
                <%= link_to 'Login', new_admin_session_path %>
            <% end %>
        <% end %>
    <% end %>
<% end %>
<div class="container" role="main">
  <%= flash_messages %>
  <%= yield %>
</div>
</body>
</html>